#spring:
  #application:
    #name: Config-default

eureka:
  instance: #indicamos la instancia
    prefer-ip-address: true
  client:
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka


test:
  JC: esto es un test
  MAIN: Esto lo agrege a main desde github
