#spring:
  #application:
    #name: Config-dev

eureka:
  instance: #indicamos la instancia
    prefer-ip-address: true
  client:
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
